---
  - name: set hostname
    tags: hostname
    hostname:
      name: "{{ guest_hostname }}"

  - name: reread facts
    tags: hostname
    setup:
  
  - name: etc hosts
    tags: hostname
    lineinfile:
      dest: /etc/hosts
      regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}"
      line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['ansible_hostname']}} {{ hostvars[item]['ansible_hostname']}}.lan"
      state: present
      backup: yes
    with_items:
      - "{{groups['guest']}}"
  
  - name: install avahi/mdns
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - avahi
      - avahi-utils
      - nss-mdns

  - name: enable avahi-daemon
    systemd:
      name: avahi-daemon
      enabled: yes
      masked: no
      state: started

  - name: restart avahi-daemon
    systemd:
      name: avahi-daemon
      state: restarted
      
