---
- name: add repo
  zypper_repository:
    repo: 'https://download.opensuse.org/repositories/devel:/languages:/go/{{ osver }}/devel:languages:go.repo'
    state: present
    runrefresh: true
    auto_import_keys: true
  when: ansible_os_family == "Suse"
  ignore_errors: yes

- name: add go
  package:
    name: go
    state: latest
