---
- hosts: guest
  vars_files: vault.yml
  gather_facts: true
  become_user: root
  become: true
  roles:
    - role: zypper
      tags: [ zypper ]
    - role: golang
      tags: [ golang ]
    - role: libvirt
      tags: [ libvirt ]
    - role: vagrant
      tags: [ vagrant ]
    - role: usermod
      tags: [ usermod ]
