---
- name: add repo
  zypper_repository:
    repo: 'https://download.opensuse.org/repositories/Virtualization/{{ osver }}/Virtualization.repo'
    state: present
    runrefresh: true
    auto_import_keys: true
  when: ansible_os_family == "Suse"
  ignore_errors: yes

- name: add libvirt
  zypper:
    name:  [ 'libvirt', 'libvirt-client', 'libvirt-bash-completion', 'qemu', 'qemu-kvm' ]
    state: latest
    disable_recommends: yes

- name: enable libvirtd
  systemd:
    name: libvirtd
    enabled: yes
    masked: no
    state: started
